### ISSUE TITLE
CPU频率选择

### ISSUE THREAD

**Issue by Oldmemorie** [chenzyadb/CuprumTurbo-Scheduler#10]
在选取频率时，优先考虑大核心吗，我该怎么做才能将大核心的频率拉升，降低中核的频率！[Screenshot_20231119-135528.png](https://github.com/chenzyadb/CuprumTurbo-Scheduler/assets/125112916/31def458-abac-47fb-99da-bcdcab0d0fb2)

**Comment by chenzyadb** [comment]
把大核对应的policy的perfMargin拉高把中核对应的policy的perfMargin拉低就行.

**Comment by Oldmemorie** [comment]
> 把大核对应的policy的perfMargin拉高把中核对应的policy的perfMargin拉低就行.

我尝试更改

**Comment by Oldmemorie** [comment]
> 把大核对应的policy的perfMargin拉高把中核对应的policy的perfMargin拉低就行.

我尝试更改perfMargin，但似乎并没有变化😅
回退7.7以后的版本得出的结果一致，在Cycles中，中核要么和大核差不多，要么超越大核，并不能像之前一样将频率区分开来，请问这属于bug还是其他因素，目前没有安装与调度冲突的模块🧐🧐![Screenshot_20231119-225146.png](https://github.com/chenzyadb/CuprumTurbo-Scheduler/assets/125112916/bb784b4b-5776-447b-8dfa-4a2861c233a9)

![Screenshot_20231119-135528.png](https://github.com/chenzyadb/CuprumTurbo-Scheduler/assets/125112916/7dcc2044-82d2-4e09-94ad-9680d544d61f)

![Screenshot_20231119-225134.png](https://github.com/chenzyadb/CuprumTurbo-Scheduler/assets/125112916/46eb740d-1d2c-4389-be9d-33a3d6636449)

![Screenshot_20231119-225121.png](https://github.com/chenzyadb/CuprumTurbo-Scheduler/assets/125112916/b398aed8-5846-49b2-a6d5-f6c50e938d89)

**Comment by chenzyadb** [comment]
可能需要把功耗限制放宽,当CPU整体满载功耗超过功耗限制之后就会按照各个policy的算力和负载重新分配最高频率, CPU频率压低后perfMargin的作用就不明显了. 或者可以直接把中核的perfScale调低让调频器认为不需要给中核分配与大核相似的频率.
