### ISSUE TITLE
支持熄屏及亮屏的動態調整嗎

### ISSUE THREAD

**Issue by cp59** [chenzyadb/CuprumTurbo-Scheduler#11]
動態調整似乎只能設定各App的調度模式
有支持設定息屏的調度模式嗎？

**Comment by Oldmemorie** [comment]
> 動態調整似乎只能設定各App的調度模式
> 有支持設定息屏的調度模式嗎？
> 

息屏状态下应该是默认模式，即_**全局默认模式**_😉😉

**Comment by chenzyadb** [comment]
熄屏状态下CPU应该是进入深度休眠模式的, 这个时候调度并不能做什么, CT会在检测到熄屏后还原内核默认的设定以避免冲突

**Comment by cp59** [comment]
但是好像Always on Display會被認為是亮屏，所以調度應該是不會被還原成內核預設的

以下是9小時AOD的耗電量 稍微有點高
![Screenshot_20231124-164006_AccuBattery](https://github.com/chenzyadb/CuprumTurbo-Scheduler/assets/51910669/8b7b60bc-5171-4306-8d19-b094951dc585)
