### ISSUE TITLE
红米K50U是8+Gen1的机器，识别成8Gen1的配置了

### ISSUE THREAD

**Issue by yinzhefuyun** [chenzyadb/CuprumTurbo-Scheduler#14]
**Describe the bug**
红米K50U是8Gen+1的机器，识别成8Gen1的配置了
**Scheduler Log:**  
- Please provide your scheduler log
这个应该不需要日志吧，调度日志里面config显示是Snapdragon8Gen1不是Snapdragon8+Gen1
**To Reproduce**
启用调度就是了
**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: 红米K50U
 - OS: Android 13 MIUI14
 - Version [v17(20231123)](https://github.com/chenzyadb/CuprumTurbo-Scheduler/releases/tag/v17(20231123))

**Comment by chenzyadb** [comment]
不知道为什么会这样,可以先从 https://github.com/chenzyadb/CuprumTurbo-Scheduler/blob/main/magisk/configs/sdm8%2Bgen1.json 下载8+GEN1的配置然后在APP导入自定义配置解决
