### ISSUE TITLE
8g3超大核 经常在0%负载下跑到2ghz+

### ISSUE THREAD

**Issue by bacon36** [chenzyadb/CuprumTurbo-Scheduler#16]
**Describe the bug**
超大核0负载无故跑到超高频，其他正常

**Scheduler Log:**  
- info级log输出全部正常。没有更细的log了。见截图

**To Reproduce**
1. 使用了tritium2.02 省电版。
2. 看b站，或者干任何事情。只有超大核的调度有问题，其余一切正常。

**Expected behavior**
正常

**Screenshots**
![1000008032](https://github.com/chenzyadb/CuprumTurbo-Scheduler/assets/7761086/b5f3e845-23ee-44f9-b674-260ce047d8bf)
![1000008029](https://github.com/chenzyadb/CuprumTurbo-Scheduler/assets/7761086/9ee555e9-0672-4bc9-8cc4-27ef84309744)
![1000008020](https://github.com/chenzyadb/CuprumTurbo-Scheduler/assets/7761086/c5ce99a6-4cf4-4eea-ba55-3cb98db6f585)
![1000008021](https://github.com/chenzyadb/CuprumTurbo-Scheduler/assets/7761086/f301af2a-e13b-4e97-aacc-1ffa4d7d52c7)
**Smartphone (please complete the following information):**
 - Device: [小米14]
 - OS: [hyperos]
 - Version [7.7.11, 7.7.12] 其他版本没有测试过

**Comment by bacon36** [comment]
复现概率极高。触发之后就会持续。之后切换应用或者一些点击操作才能降回来。如果不点击屏幕，就永远不回来了。

**Comment by chenzyadb** [comment]
应该是澎湃OS的调度把CT设置的CPU频率给覆盖了, 后面想办法修复吧
