### ISSUE TITLE
CuprumTurbo Scheduler是否支持更改CPU工作模式

### ISSUE THREAD

**Issue by Oldmemorie** [chenzyadb/CuprumTurbo-Scheduler#17]
尊敬的开发者，您好，我存在一些疑问：

- CuprumTurbo Scheduler 在工作中是否允许更改CPU模式，例如**scheduitl，performance, powersave等**
- 在启动CuprumTurbo Scheduler后，默认使用**performance**工作模式，我尝试更改其工作模式，但很快便会恢复到performance，请问是否有方法更改工作模式
![IMG20231225233207.jpg](https://github.com/chenzyadb/CuprumTurbo-Scheduler/assets/125112916/1fd6cc00-c106-4367-9bbe-aecca2740b14)

非常抱歉占用您宝贵的时间，感谢您的回复

**Comment by chenzyadb** [comment]
不能,CT就是依靠设置内核调频器为performance然后使用用户态调频器接管来实现CpuGovernor的功能的.如果需要使用内核调频器就修改配置文件把CpuGovernor模块禁用即可

**Comment by Oldmemorie** [comment]
> 不能,CT就是依靠设置内核调频器为performance然后使用用户态调频器接管来实现CpuGovernor的功能的.如果需要使用内核调频器就修改配置文件把CpuGovernor模块禁用即可

感谢您的解答
