### ISSUE TITLE
监测掉帧的模块无法安装使用

### ISSUE THREAD

**Issue by dty285767** [chenzyadb/CuprumTurbo-Scheduler#19]
这个模块是受限于安卓版本吗  目前是安卓11   
另外想问下后续有没有可能向下兼容

**Comment by chenzyadb** [comment]
安卓12大改了SurfaceFlinger的设计，所以掉帧监测模块不能用在低于安卓12的系统中。适配低版本安卓需要重新写一套方案，所以暂时不考虑适配。
