### ISSUE TITLE
K60u miui14.0.14添加自定义配置文件直接闪退

### ISSUE THREAD

**Issue by yuan6975** [chenzyadb/CuprumTurbo-Scheduler#20]
**Describe the bug**

**Scheduler Log:**  
- Please provide your scheduler log

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Redmi  k60u]
 - OS: [e.g. Android 13 MIUI14]
 - Version [e.g. V14]
选择添加自定义配置的加号就闪退,软件给了root权限,没有申请储存空间权限,手动也没有找到软件的权限请求

**Comment by yuan6975** [comment]
软件版本试了8.0.11 8.0.10都是一样的情况

**Comment by yuan6975** [comment]
7.7.14版本选择导入弹窗   《调用SAF失败》

**Comment by chenzyadb** [comment]
安卓默认的文件应用(com.android.documentui)被删掉了所以调用不了SAF导致的，不是应用自身的问题
