### ISSUE TITLE
解除性能限制模块导致zygisk无法加载

### ISSUE THREAD

**Issue by huaaaajjj** [chenzyadb/CuprumTurbo-Scheduler#21]
**Describe the bug**
Kitsune Mask安装拓展功能中的模块导致zygisk无法加载，重启之后也不行，经过排查，是解除性能限制模块

**Scheduler Log:**  
[magisk_log_2024-05-17T104914.zip](https://github.com/chenzyadb/CuprumTurbo-Scheduler/files/15343836/magisk_log_2024-05-17T104914.zip)

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot_2024-05-17-12-56-43-871_io github huskydg magisk](https://github.com/chenzyadb/CuprumTurbo-Scheduler/assets/170057899/f76a574c-0fa9-449e-adbf-10f60b931f1e)
![Screenshot_2024-05-17-12-56-37-745_io github huskydg magisk](https://github.com/chenzyadb/CuprumTurbo-Scheduler/assets/170057899/dcab7e8a-1969-471d-a31f-f0f994ae6ce9)

**Smartphone (please complete the following information):**
 - Device: [Xiaomi 9]
 - OS: [V14 HyperOs1.0.6]
 - Version [8.0.13]

**Comment by Suni-code** [comment]
可以用其他去温控模块代替此 模块 此模块非必装模块
