### ISSUE TITLE
关于D9200/D9200+的8.1.0Beta问题

### ISSUE THREAD

**Issue by XiaHuaBeiChiDiaoLe** [chenzyadb/CuprumTurbo-Scheduler#22]
无法正常启用调度
日志大约写的是找不到超大核 第2集群
默认自带和改后的配置文件都是一样

**Comment by chenzyadb** [comment]
需要有日志的截图才能确定是什么问题

**Comment by XiaHuaBeiChiDiaoLe** [comment]
![Uploading Screenshot_2024-05-23-12-10-16-181_xyz.chenzyadb.cu_toolbox.jpg…]()

**Comment by XiaHuaBeiChiDiaoLe** [comment]
![Screenshot_2024-05-23-12-10-16-181_xyz chenzyadb cu_toolbox](https://github.com/chenzyadb/CuprumTurbo-Scheduler/assets/102962613/5e38bcb3-0095-48de-ba3f-77689a28b669)

**Comment by chenzyadb** [comment]
这个是在新版本内核上找不到联发科helio-dvfsrc的目录,下个版本会修.

**Comment by XiaHuaBeiChiDiaoLe** [comment]
好的 感谢付出
