### ISSUE TITLE
版本 CuToolbox V8.1.4 Release  动画卡顿

### ISSUE THREAD

**Issue by dty285767** [chenzyadb/CuprumTurbo-Scheduler#25]
这版更新后测试  电流波动确实是小了 但是开高刷滑动感觉动画卡卡的  不流畅 遂退回7714版本
处理器是 天玑1200 
还有个小问题 就是新版的通知栏能否改回7版本这种带显示电流的  看电流比较方便

**Comment by chenzyadb** [comment]
在同样是天玑1200的K40G上使用 APP v8.1.4 + 掉帧监测模块v1.8 基本上没有出现过滑动掉帧的问题.
如果有能力修改配置文件的话把FreqBurst的durationTime调高应该可以解决.
在APP V8版本重写的时候已经把和调度无关的功能都精简掉了,性能监视悬浮窗和CumulusAPP都可以监测电流.
