### ISSUE TITLE
怎样设置一个核心频率最大值呢

### ISSUE THREAD

**Issue by QQJemRun** [chenzyadb/CuprumTurbo-Scheduler#26]
我希望能够在固定的cpu频率表中挑选一个最大值，希望ct调度cpu时不要超过这个最大值，请问我需要怎么做？
文档中仅给出了最大值限制为功耗限制，这个限制仿佛并不能帮我将频率最大值固定。
我也修改了policy中的modelfreq，也不能达到想要的效果，在调度过程中依旧会有跃进达到cpu频率表的最大值。
请指教。

**Comment by chenzyadb** [comment]
ct不具备设置CPU频率最大值的功能, CPU频率的最大值是根据场景动态调整的.

**Comment by QQJemRun** [comment]
i do know this,but is there any way can i set the maximum value in regulation？

**Comment by chenzyadb** [comment]
Given the current design, achieving this goal is not possible.

**Comment by QQJemRun** [comment]
that's really a pity.thanks for your reply!
