### ISSUE TITLE
看到文档最后面有场景写入器，想问ct是否本身支持动态调整模式。

### ISSUE THREAD

**Issue by ixaobao** [chenzyadb/CuprumTurbo-Scheduler#27]
看文档只是简单介绍了一下，是否能实现屏幕点亮触发均衡模式，关闭屏幕时触发省电模式呢，自己尝试理解写了一下，都无法运行报错。请求支持一下magisk版的动态模式。

**Comment by NightRainMilkyWay** [comment]
可以使用FileWriter模块满足你的需求![IMG_20240727_233858.jpg](https://github.com/user-attachments/assets/990cbd18-9fa9-431b-9c03-355ddc1f1d6b)

**Comment by ixaobao** [comment]
我也是这样理解的，也是这么写的，但是报错哇，重启之后log只有一条07-27 23:53:08 [I] Daemon stop running.

**Comment by ixaobao** [comment]
![微信图片_20240728000444](https://github.com/user-attachments/assets/7fb1260c-3365-4abf-a2ea-f544a77b9470)
![微信图片_20240728000453](https://github.com/user-attachments/assets/9b095d64-b8b7-44dc-98ae-c6da775dfd9e)
这样的

**Comment by NightRainMilkyWay** [comment]
> ![微信图片_20240728000444](https://github.com/user-attachments/assets/7fb1260c-3365-4abf-a2ea-f544a77b9470)
> ![微信图片_20240728000453](https://github.com/user-attachments/assets/9b095d64-b8b7-44dc-98ae-c6da775dfd9e)
> 这样的

我给出的示例并不严谨，请把多余的_**,**_
去掉

**Comment by ixaobao** [comment]
> > ![微信图片_20240728000444](https://github.com/user-attachments/assets/7fb1260c-3365-4abf-a2ea-f544a77b9470)
> > ![微信图片_20240728000453](https://github.com/user-attachments/assets/9b095d64-b8b7-44dc-98ae-c6da775dfd9e)
> > 这样的
> 
> 我给出的示例并不严谨，请把多余的`,`
> 去掉

我后面用ai修正了，不报错但是看log不会切换😂

**Comment by chenzyadb** [comment]
CT调度在待机的时候不会工作, 待机的时候切换调度模式是没有意义的.
