### ISSUE TITLE
Heating

### ISSUE THREAD

**Issue by Myehia201** [chenzyadb/CuprumTurbo-Scheduler#28]
Everything is good until i open a game the device heats alot and it never happened with me before 

**Smartphone (please complete the following information):**
 - Device: [OnePlus 12]
 - OS: [A14 ColorOS 14]
 - snapdragon 8gen3

**Comment by chenzyadb** [comment]
Because this scheduling prioritizes performance over heating control, you might want to try adjusting to 'balance' or 'powersave' mode. If that doesn't work, you can manually modify the 'overHeatTemp' parameter in the configuration file.
