### ISSUE TITLE
无法获取到gpu频率接口

### ISSUE THREAD

**Issue by 319016** [chenzyadb/CuprumTurbo-Scheduler#29]
**Describe the bug**
A clear and concise description of what the bug is
“v19版本不管是软件自带的调度文件，还是第三方的调度文件,都没有办法获取到Gpu的频率接口，而v18的版本能获取得了(官方的和第三方的调度都可以),”.

**Scheduler Log:**  
- Please provide your scheduler log
- 请见截屏
- V18的
![Screenshot_20240809-132926_CuToolbox](https://github.com/user-attachments/assets/deb0c51c-cdf4-471c-a69b-cfcd63a96c14)
V19的
![Screenshot_20240809-133959_CuToolbox](https://github.com/user-attachments/assets/8beae0e3-9550-40c1-8bd8-9204d341366a)
![Screenshot_20240809-134003_CuToolbox](https://github.com/user-attachments/assets/64802ca9-ad43-4800-961c-0a3701b27bc2)
![Screenshot_20240809-134132_CuToolbox](https://github.com/user-attachments/assets/07ed420f-f221-4f09-a3c7-390ab15869c9)
![Screenshot_20240809-134135_CuToolbox](https://github.com/user-attachments/assets/c407b3cb-c6b6-44d0-8e08-883e49a5ff87)
![Screenshot_20240809-134149_Ortus Launcher](https://github.com/user-attachments/assets/d5a5f9a0-60f7-4c1b-be8a-057ddb3c4758)

**Smartphone (please complete the following information):**
 - Device: [Redmi note 8 Pro]
 - OS: [Android 13 risingos1.4（类原生）]
 - Version [V19]
 - 
![Screenshot_20240809-234452_设置](https://github.com/user-attachments/assets/d150429d-24c1-46a3-8540-2670ebd2f235)
![Screenshot_20240809-234505_设置](https://github.com/user-attachments/assets/55259955-eb53-41ec-8420-0df7d48ccebc)

**Comment by chenzyadb** [comment]
可能是内核不支持gpufreq_aging_enable导致的, 下个版本会修复.
