### ISSUE TITLE
最低从8.1.8开始，启动调度优化后不久会自行关闭

### ISSUE THREAD

**Issue by ctrlkk** [chenzyadb/CuprumTurbo-Scheduler#30]
**Describe the bug**
最低从8.1.8开始，启动调度优化后不久会自行关闭，该BUG出现在_8.1.8_,_8.1.10_,_8.19_
更多版本未经测试，7.7.5中正常运行

**Scheduler Log:**  
09-14 19:09:07 [I] CuprumTurbo Scheduler V19 (20240714)by chenzyadb.09-14 19:09:07 [I] Config "Dimensity7200" by"chenzyadb".09-14 19:09:07 [I]CpuGovernor is enabled.09-14 19:09:07 [I] ThreadSched0pt is enabled.09-14 19:09:077[I] MtkGpuGovernor is enabled.09-14 19:09:07 [I] FileWriter is enabled.09-1419:09:077[I] Policyθ （CPUo-5） PowerModel:09-1419:09:07[I]1Idx=0，Freq=550 MHz，Power=60 mW.09-14 19:09:07[I]1Idx=1，Freq=750 MHz， Power=93 mW.09-14 19:09:07[I]1Idx=2， Freq=950 MHz， Power=132 mW.09-14 19:09:07[I]Idx=3，Freq=1150 MHz，Power=178 mW.09-14 19:09:07[I]Idx=4，Freq=1350 MHz，Power=231 mW.09-14 19:09:07[I]1 Idx=5， Freq=1550 MHz， Power=292 mW.09-1419:09:077[I] Idx=6， Freq=1750 MHz， Power=372 mW.09-1419:09:077[I] Idx=7，Freq=1950 MHz， Power=472 mW.09-1419:09:07[I]] Idx=8，Freq=200θ MHz， Power=500mW.09-1419:09:07[I]1Policy1（CPU6-7)PowerModel:09-14 19:09:07[I]]Idx=0，Freq=700 MHz，Power=127mW.09-14 19:09:07[I]]Idx=1， Freq=900 MHz， Power=183 mW.09-14 19:09:07[I]Idx=2，Freq=1100 MHz，Power=250 mW.09-14 19:09:07[I]Idx=3，Freq=1300 MHz，Power=328 mW.09-14 19:09:07[I]Idx=4， Freq=1500 MHz， Power=417 mW.09-1419:09:07[I]Idx=5， Freq=1700 MHz， Power=519 mW.09-1419:09:07[I]]Idx=6， Freq=1900 MHz， Power=673 mW.09-1419:09:07[I]]Idx=7，Freq=2100 MHz,Power=841mW.09-1419:09:07[I]]Idx=8，Freq=2300 MHz， Power=1035 mW.09-1419:09:07[I]]Idx=9，Freq=2500 MHz， Power=1255 mW.09-1419:09:07[I]1Idx=10，Freq=2700 MHz， Power=1504 mW.09-1419:09:077[I] Idx=11， Freq=2800 MHz， Power=1640 mW.09-14 19:09:07 [E] No available CpuFreqWriter found.09-14 19:09:08 [I] Daemon stop running.

**Screenshots**
![recording](https://github.com/user-attachments/assets/3e2c8696-888e-40ba-8622-7c1a2d2950fc)
![image](https://github.com/user-attachments/assets/f705075a-3731-4af4-a196-dac00a22bea7)

**Smartphone (please complete the following information):**
 - Device: [Redmi note 13 pro+]
 - OS: [Android 13 MIUI14.0.4]
 - Version [8.0.10]

**Comment by chenzyadb** [comment]
应该是是系统调度/云控/温控限制了CPU频率导致的，MIUI14应该还可以关闭温控和云控

**Comment by ctrlkk** [comment]
> 应该是是系统调度/云控/温控限制了CPU频率导致的，MIUI14应该还可以关闭温控和云控

在使用adb冻结joyose并安装扩展功能内的解除温度控制模块后，CuprumTurbo依旧无法按照预期运行，并且未出现error日志
![d329ec5d6dc0d5b0793c67b4e0aadfb](https://github.com/user-attachments/assets/d07f672e-091d-46ed-831d-ed9760e38601)

**Comment by NightRainMilkyWay** [comment]
> > 应该是是系统调度/云控/温控限制了CPU频率导致的，MIUI14应该还可以关闭温控和云控
> 
> 在使用adb冻结joyose并安装扩展功能内的解除温度控制模块后，CuprumTurbo依旧无法按照预期运行，并且未出现error日志
> ![d329ec5d6dc0d5b0793c67b4e0aadfb](https://github.com/user-attachments/assets/d07f672e-091d-46ed-831d-ed9760e38601)
> 

可以检查下是否使用墓碑，冻结应用程序类，例如**noactive，thanox**等，是否设置`白名单`

**Comment by chenzyadb** [comment]
> > 应该是是系统调度/云控/温控限制了CPU频率导致的，MIUI14应该还可以关闭温控和云控
> 
> 在使用adb冻结joyose并安装扩展功能内的解除温度控制模块后，CuprumTurbo依旧无法按照预期运行，并且未出现error日志 ![d329ec5d6dc0d5b0793c67b4e0aadfb](https://private-user-images.githubusercontent.com/88469720/367582170-d07f672e-091d-46ed-831d-ed9760e38601.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MTQ3MTksIm5iZiI6MTcyNjQxNDQxOSwicGF0aCI6Ii84ODQ2OTcyMC8zNjc1ODIxNzAtZDA3ZjY3MmUtMDkxZC00NmVkLTgzMWQtZWQ5NzYwZTM4NjAxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDE1MzMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmOWQ1ZDllMjAzOWUwOTk3YTQxMTg3N2ZiYjQ2NTZlZjUwY2Y0MTA0OTAyNDUyOGM2Y2ZkN2VmYzYxM2I3MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rVOG2ed-M1RN29fsoZHGSLzbxditxKKSYK8K6jSuEbA)


可能是联发科又更新了接口导致的, 我目前手上只有天玑9000作为参考. 如果能提供一下/proc/gpufreqv2目录下面的文件列表和文件内容, 应该可以修复这个问题.

**Comment by ctrlkk** [comment]
> > > 应该是是系统调度/云控/温控限制了CPU频率导致的，MIUI14应该还可以关闭温控和云控
> > 
> > 
> > 在使用adb冻结joyose并安装扩展功能内的解除温度控制模块后，CuprumTurbo依旧无法按照预期运行，并且未出现error日志   ![d329ec5d6dc0d5b0793c67b4e0aadfb](https://private-user-images.githubusercontent.com/88469720/367582170-d07f672e-091d-46ed-831d-ed9760e38601.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MTQ3MTksIm5iZiI6MTcyNjQxNDQxOSwicGF0aCI6Ii84ODQ2OTcyMC8zNjc1ODIxNzAtZDA3ZjY3MmUtMDkxZC00NmVkLTgzMWQtZWQ5NzYwZTM4NjAxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDE1MzMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmOWQ1ZDllMjAzOWUwOTk3YTQxMTg3N2ZiYjQ2NTZlZjUwY2Y0MTA0OTAyNDUyOGM2Y2ZkN2VmYzYxM2I3MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rVOG2ed-M1RN29fsoZHGSLzbxditxKKSYK8K6jSuEbA)
> 
> 可能是联发科又更新了接口导致的, 我目前手上只有天玑9000作为参考. 如果能提供一下/proc/gpufreqv2目录下面的文件列表和文件内容, 应该可以修复这个问题.

当然可以，这是问题设备下`/proc/gpufreqv2`的副本
[gpufreqv2.zip](https://github.com/user-attachments/files/17008268/gpufreqv2.zip)

**Comment by ctrlkk** [comment]
> > > 应该是是系统调度/云控/温控限制了CPU频率导致的，MIUI14应该还可以关闭温控和云控
> > 
> > 
> > 在使用adb冻结joyose并安装扩展功能内的解除温度控制模块后，CuprumTurbo依旧无法按照预期运行，并且未出现error日志 
> 可以检查下是否使用墓碑，冻结应用程序类，例如** _noactive，thanox _**等，是否设置 `白名单`

并没有使用任何第三方软件，仅使用adb命令禁用joyose
```shell
adb shell pm disable-user com.xiaomi.joyose
```

**Comment by chenzyadb** [comment]
V8.1.11 已修复.

**Comment by ctrlkk** [comment]
> V8.1.11 已修复.

谢谢，8.1.11已经可以在我的设备上正常运行了❤👍
