### ISSUE TITLE
与HyperCleiler冲突

### ISSUE THREAD

**Issue by baik9121** [chenzyadb/CuprumTurbo-Scheduler#31]
这个应用里的解除性能限制模块在HyperOS1.0.42版本以上与HyperCleiler冲突，我用的是Zygisk加载的HyperCleiler，在magisk27008中同时应用Zygisk和解除性能限制模块后，Zygisk会显示未加载，经过排除确定与HyperCleiler  v2.4.148冲突，还请优化，感谢！

**Comment by chenzyadb** [comment]
这个模块只会简单地替换一些系统温控文件, 不知道是什么原因导致的冲突. CT并不依赖这个模块工作, 而且在MIUI上它的效果也不好, 如果有需要可以用其他温控移除模块代替掉它.
