### ISSUE TITLE
helio g90t开启极速模式时,会死机

### ISSUE THREAD

**Issue by 319016** [chenzyadb/CuprumTurbo-Scheduler#32]
**Describe the bug**
A clear and concise description of what the bug is
 8.1.11_release在redmi note 8 pro，无论是类原生risingos，还是官方rom,在调度模式选为极速时，手机会定屏死机，其他模式就不会.

**Scheduler Log:**  
- Please provide your scheduler log
- 
![Screenshot_2024-09-30-13-32-26-037_xyz chenzyadb cu_toolbox](https://github.com/user-attachments/assets/d4d6d1d5-0831-4995-a290-9dbd5db681cd)

**Smartphone (please complete the following information):**
 - Device: [Redmi note 8  Pro]
 - OS: [Android 14 Hyperos1.0.17.0.UGGCNXM]
 - Version [V19]
 - 
![Screenshot_2024-09-30-13-30-32-941_com android settings](https://github.com/user-attachments/assets/28839487-d423-438c-934b-f10a9373285c)

**Comment by Suni-code** [comment]
提供下长截图 我看看🧐

**Comment by 319016** [comment]
> 提供下长截图 我看看🧐

![Screenshot_2024-09-30-19-09-07-905_xyz chenzyadb cu_toolbox](https://github.com/user-attachments/assets/355363b9-6250-4d06-b61b-9860816b06b9)
![Screenshot_2024-09-30-19-09-10-894_xyz chenzyadb cu_toolbox](https://github.com/user-attachments/assets/bc36d671-39d9-4e6d-9155-aed641482eda)

**Comment by 319016** [comment]
V8.1.10 正式版，之前从这个版本（修复了那个gpu的接口）就开始了这个问题，只不过一直都是省电模式下使用，就忘了反馈了，现在打游戏再次遇到才想起来。换了系统还不行😭

**Comment by chenzyadb** [comment]
是刚一切换模式就死机？性能模式不会出现这个问题吗？GPU电压表看起来是被动过的，是不是因为降压导致的死机呢？

**Comment by 319016** [comment]
> 是刚一切换模式就死机？性能模式不会出现这个问题吗？GPU电压表看起来是被动过的，是不是因为降压导致的死机呢？

切换后大概一分钟之内,性能模式不会有这个问题,对比过降压、没降压两种情况在极速模式下都会

**Comment by chenzyadb** [comment]
也有可能是极速模式撞内核温度墙了. 极速模式和性能模式基本上只有温度控制上的差距, 如果是程序本身上的缺陷不太可能性能模式没问题就极速模式出问题.

**Comment by 319016** [comment]
> 也有可能是极速模式撞内核温度墙了. 极速模式和性能模式基本上只有温度控制上的差距, 如果是程序本身上的缺陷不太可能性能模式没问题就极速模式出问题.

有没有可能是频率瞬时没有跟上去呢？切换了极速模式玩游戏（和平精英）的时候还没有开局，一切正常，直到开始战斗，就瞬间定屏，电池温度37度，在定屏瞬间看到Gpu拉满但频率处于较低档位, Cpu只占50%,极速模式下，好像gpu并不会自动达到最高档位。
而性能模式下，就不会有这些问题（不是很清楚原因）

**Comment by Suni-code** [comment]
删温控了吗@319016

**Comment by 319016** [comment]
> 删温控了吗@319016

已删

**Comment by 319016** [comment]
极速模式下，Gpu的频率好像总是上不去，很容易就会拉满，用sence可以看到极速模式下Gpu的频率甚至不够性能模式下高,不知道是不是因为gpu的拉满了,导致的定屏（因为定屏的时候已经无法刷新了，看不到频率变化，只能偶尔看到定屏前的几秒，cpu一直保持占用在50%左右（打游戏时））

**Comment by 319016** [comment]
我似乎排除出原因了!
![Screenshot_2024-10-16-18-55-35-480_bin mt plus](https://github.com/user-attachments/assets/df25fdce-5956-4a36-9d45-5a3e178477c8)
这样改（关掉对gpu的调度），就不会在极速模式下定屏死机了

**Comment by chenzyadb** [comment]
会改配置文件的话直接把performance的参数复制粘贴到fast模式那不就解决了...

**Comment by 319016** [comment]
> 会改配置文件的话直接把performance的参数复制粘贴到fast模式那不就解决了...

只能找到这些总的开关字段，两个模式的Gpu的参数找不明白…

**Comment by 319016** [comment]
![Screenshot_2024-10-21-18-40-54-444_bin mt plus](https://github.com/user-attachments/assets/8cae9b1b-e081-4899-9f1e-bb8ea8170ae7)
![Screenshot_2024-10-21-18-44-31-201_com omarea vtools](https://github.com/user-attachments/assets/86cc4074-a0d7-40fc-bb1c-b693f2ee96f2)
Gpu的最高频率只有806,但是默认配置里面写的是810。在测试中，发现810改成792，能有效缓解定屏死机（基本不会再出现）。发现每次卡死之前， Gpu的使用率总是达到100%，估测应该是长时间100%。但是如果gpu由系统去调整的话，长时间100%，也不会定屏死机（很奇怪🌚）
